[package]
name = "pdf-wlx-qt5"
version = "0.3.0"
edition = "2021"
license = "EUPL-1.2 OR GPL-2.0-or-later OR AGPL-3.0-or-later"
build = "build.rs"

[features]
default = ["poppler-splash"]
poppler-splash = []
mutool = []

[lib]
crate-type = ["cdylib"]

[build-dependencies]
cc = "1.2"
pkg-config = "0.3"
